config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Motor::Admin => '/motor_admin'
  mount Sidekiq::Web => '/sidekiq'
  mount GoodJob::Engine => 'good_job'

  draw(:installation)

  resources :accounts, module: :accounts do
    resources :webpush_subscriptions, only: [:create]
    resources :settings, only: [:index]
    resources :welcome, only: [:index]
    resources :custom_attributes_definitions, module: :settings do
    end

    resources :webhooks, module: :settings do
    end

    resources :users do
      get 'select_user_search', on: :collection
    end
    resources :products do
      get 'edit_custom_attributes', on: :member
      patch 'update_custom_attributes', on: :member
      get 'select_product_search', on: :collection
    end
    resources :contacts do
      get 'search', to: 'contacts#search', on: :collection
      get 'edit_custom_attributes'
      get 'chatwoot_conversation_link', on: :member
      patch 'update_custom_attributes'
      get 'select_contact_search', on: :collection
      resources :events, module: :contacts do
      end
      namespace :events, module: :contacts do
        namespace :apps, module: :events do
        end
      end

      collection do
        resources :chatwoot_embed, only: %i[show new create], controller: 'contacts/chatwoot_embed' do
          post 'search', on: :collection
        end
      end
      get 'hovercard_preview', on: :member
    end
    resources :pipelines do
      get 'import'
      post 'import_file'
      get 'export'
      member do
        get 'new_bulk_action'
        get 'bulk_action'
        post 'create_bulk_action'
      end
    end

    resources :deals do
      patch 'update_deal_product', on: :member
      get 'edit_deal_product', on: :member
      get 'deal_products', on: :member
      get 'deal_assignees', on: :member
      get 'events_to_do', on: :member
      get 'events_done', on: :member
      get 'add_contact'
      post 'commit_add_contact'
      delete 'remove_contact'
      get 'new_select_contact', on: :collection
      get 'edit_custom_attributes'
      patch 'update_custom_attributes'
    end
    resources :deal_products, only: %i[destroy new create]
    resources :deal_assignees, only: %i[destroy new create]

    namespace :apps do
      resources :evolution_apis do
        member do
          get 'pair_qr_code'
          post 'refresh_qr_code'
        end
      end
      resources :chatwoots
      # resources :events, module: :contacts
      resource :ai_assistent, only: %i[edit update]
    end
    resources :attachments, only: [:destroy]
    resources :stages, only: [:show]
  end
  if ENV.fetch('ENABLE_USER_SIGNUP', 'false') == 'true'
    devise_for :users, controllers: {
      registrations: 'users/registrations'
    }
  else
    devise_for :users, skip: [:registrations]
  end

  root to: 'accounts/pipelines#index'

  namespace :api do
    namespace :v1 do
      resources :accounts, module: :accounts do
        resources :deals, only: %i[show create update] do
          post 'upsert', on: :collection
          resources :events, only: [:create], module: :deals do
          end
        end
        resources :contacts, only: %i[show create] do
          post 'upsert', on: :collection
          match 'search', on: :collection, via: %i[get post]
        end
        namespace :apps do
          # resources :events, module: :contacts
        end
        resources :deal_products, only: %i[create show]
        resources :products, only: %i[create show] do
          match 'search', on: :collection, via: %i[get post]
        end
      end

      resources :contacts, only: [:create] do
      end
    end
  end

  namespace :embedded do
    resources :accounts, module: :accounts do
      namespace :apps do
        resources :chatwoots, only: [:index] do
        end
      end
    end
  end

  namespace :apps do
    resources :chatwoots do
      collection do
        post 'webhooks'
        get 'embedding'
        get 'embedding_init_authenticate'
        post 'embedding_authenticate'
      end
    end
    resources :evolution_apis do
      collection do
        post 'webhooks'
      end
    end
  end
  get 'service-worker' => 'pwa#service_worker'
  get 'webmanifest' => 'pwa#manifest'
end

app/models/concerns/deal/broadcastable.rb
module Deal::Broadcastable
  extend ActiveSupport::Concern
  included do
    after_create_commit do
      if done == false
        broadcast_prepend_later_to [contact_id, 'events'],
                                   partial: 'accounts/contacts/events/event',
                                   target: "events_to_do_#{contact.id}"
      else
        broadcast_prepend_later_to [contact_id, 'events'],
                                   partial: 'accounts/contacts/events/event',
                                   target: "events_done_#{contact.id}"
      end
    end

    def broadcast_events
      events_to_do = deal.contact.events.to_do.limit(5).to_a
      events_done = deal.contact.events.done.limit(5).to_a
      broadcast_replace_later_to [contact_id, 'events'], target: "events_to_do_#{contact.id}",
                                                         partial: 'accounts/contacts/events/events_to_do', locals: { deal: deal, events: events_to_do, pagy: 1 }
      broadcast_replace_later_to [contact_id, 'events'], target: "events_done_#{contact.id}",
                                                         partial: 'accounts/contacts/events/events_done', locals: { deal: deal, events: events_done, pagy: 1 }
    end

    after_update_commit do
      if saved_change_to_done_at?
        broadcast_events
      else
        broadcast_replace_later_to [contact_id, 'events'],
                                   partial: 'accounts/contacts/events/event'
      end
    end

    after_destroy_commit do
      broadcast_remove_to [contact_id, 'events']
    end
  end
end

app/models/concerns/deal/decorators.rb
module Deal::Decorators
  include ActionView::Helpers::NumberHelper

  def card_total_amount_resume
    number_to_human((total_amount_in_cents / 100.0), units: { thousand: 'K', million: 'M', billion: 'B' })
  end

  def card_total_amount_detail
    number_to_currency(
      (total_amount_in_cents / 100.0), separator: ',', delimiter: '.', precision: 2
    )
  end
end

app/models/concerns/deal/event_creator.rb
module Deal::EventCreator
  extend ActiveSupport::Concern
  included do
    around_create :create_deal_and_event
    around_update :update_deal_and_create_event

    def create_deal_and_event
      transaction do
        yield
        create_event_log('deal_opened')
      end
    end

    def update_deal_and_create_event
      transaction do
        yield
        create_event_based_on_changes
      end
    end

    def create_event_based_on_changes
      return create_event_log('deal_won') if status_previously_changed?(to: 'won')
      return create_event_log('deal_lost') if status_previously_changed?(to: 'lost')
      return create_event_log('deal_reopened') if status_previously_changed?(to: 'open')

      create_event_log_stage_changes if stage_previously_changed?
    end
  end

  private

  def create_event_log_stage_changes
    old_stage_id, new_stage_id = previous_changes['stage_id']
    old_stage = Stage.find_by(id: old_stage_id) if old_stage_id
    new_stage = Stage.find_by(id: new_stage_id) if new_stage_id

    Event.create!(
      deal: self,
      kind: 'deal_stage_change',
      done: true,
      contact:,
      from_me: true,
      additional_attributes: {
        old_stage_id: old_stage.id,
        old_stage_name: old_stage.name,
        old_stage_pipeline_id: old_stage.pipeline.id,
        old_stage_pipeline_name: old_stage.pipeline.name,
        new_stage_id: new_stage.id,
        new_stage_name: new_stage.name,
        new_stage_pipeline_id: new_stage.pipeline.id,
        new_stage_pipeline_name: new_stage.pipeline.name,
        deal_name: name
      }
    )
  end

  def create_event_log(log_kind)
    Event.create!(
      deal: self,
      kind: log_kind,
      done: true,
      from_me: true,
      contact:,
      additional_attributes: {
        stage_id: stage.id,
        stage_name: stage.name,
        pipeline_id: pipeline.id,
        pipeline_name: pipeline.name,
        deal_name: name
      }
    )
  end
end

app/models/concerns/deal/handle_in_cents_values.rb
module Deal::HandleInCentsValues
  extend ActiveSupport::Concern
  included do
    %i[
      total_amount_in_cents
    ].each do |attribute|
      define_method("#{attribute}=") do |amount|
        amount = sanitize_amount(amount)
        super(amount)
      end
    end
  end
end

app/models/concerns/deal/presenters.rb
module Deal::Presenters
  include ActionView::Helpers::NumberHelper
  extend ActiveSupport::Concern

  def total_deal_products_amount_in_cents_at_format
    number_to_currency(total_deal_products_amount_in_cents / 100.0, unit: 'R$', separator: ',', delimiter: '.')
  rescue StandardError
    ''
  end

  def total_amount_in_cents_at_format
    number_to_currency(total_amount_in_cents / 100.0, unit: 'R$', separator: ',', delimiter: '.')
  rescue StandardError
    ''
  end
end

app/models/deal/create_or_update.rb
class Deal::CreateOrUpdate
  def initialize(deal, params)
    @deal = deal
    @params = params
  end

  def call
    @deal.assign_attributes(@params)
    return false if @deal.invalid?

    set_lost_at_and_won_at if should_update_lost_at_or_won_at?
    @deal.save!
    @deal
  end

  private

  def should_update_lost_at_or_won_at?
    @deal.status_changed? || @deal.new_record?
  end

  def set_lost_at_and_won_at
    if @deal.won?
      @deal.won_at = Time.current
      @deal.lost_at = nil
    elsif @deal.lost?
      @deal.lost_at = Time.current
      @deal.won_at = nil
    else
      @deal.lost_at = nil
      @deal.won_at = nil
    end
  end
end

app/models/deal/recalculate_and_save_all_monetary_values.rb
class Deal::RecalculateAndSaveAllMonetaryValues
  def initialize(deal)
    @deal = deal
  end

  def call
    ActiveRecord::Base.transaction do
      recalculate_deal
    end
  end

  private

  def recalculate_deal
    @deal.total_deal_products_amount_in_cents = @deal.deal_products.sum(:total_amount_in_cents)
    @deal.save!
  end
end

app/controllers/accounts/deals_controller.rb
class Accounts::DealsController < InternalController
  include DealProductConcern

  before_action :set_deal,
                only: %i[show edit update destroy events_to_do events_done deal_products deal_assignees]
  before_action :set_deal_product, only: %i[edit_deal_product
                                            update_deal_product]

  # GET /deals or /deals.json
  def index
    @first_pipeline = Pipeline.first
    @deals = if params[:query].present?
              Deal.left_joins(:contact)
                  .where(
                    'deals.name ILIKE :search OR ' +
                    'contacts.full_name ILIKE :search OR ' +
                    'deals.id = :id',
                    search: "%#{params[:query]}%",
                    id: params[:query].to_i
                  )
                  .order(updated_at: :desc)
              else
                Deal.all.order(created_at: :desc)
              end

    @pagy, @deals = pagy(@deals)
  end

  # GET /deals/1 or /deals/1.json
  def show; end

  # GET /deals/new
  def new
    @deal = Deal.new
    @stages = current_user.account.stages
    @deal.contact_id = params[:deal][:contact_id]
  end

  def new_select_contact
    @deal = Deal.new
  end

  def add_contact
    @deal = Deal.find(params[:deal_id])
  end

  def commit_add_contact
    @deal = Deal.find(params[:deal_id])
    @new_contact = Contact.find(params['deal']['contact_id'])
    @deal.contacts.push(@new_contact)

    if Deal::CreateOrUpdate.new(@deal, deal_params).call
      redirect_to account_deal_path(current_user.account, @deal)
    else
      render :add_contact, status: :unprocessable_entity
    end
  rescue StandardError
    render :add_contact, status: :unprocessable_entity
  end

  def remove_contact
    @deal = Deal.find(params[:deal_id])
    @contacts_deal = @deal.contacts_deals.find_by_contact_id(params['contact_id'])

    if @contacts_deal.destroy
      redirect_to account_deal_path(current_user.account, @deal)
    else
      render :show, status: :unprocessable_entity
    end
  rescue StandardError
    render :show, status: :unprocessable_entity
  end

  # GET /deals/1/edit
  def edit
    @stages = current_user.account.stages
  end

  def edit_custom_attributes
    @deal = current_user.account.deals.find(params[:deal_id])
    @custom_attribute_definitions = current_user.account.custom_attribute_definitions.deal_attribute
  end

  # POST /deals or /deals.json
  def create
    @stages = current_user.account.stages
    @deal = DealBuilder.new(current_user, deal_params).perform

    if Deal::CreateOrUpdate.new(@deal, deal_params).call
      redirect_to account_deal_path(current_user.account, @deal)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /deals/1 or /deals/1.json
  def update
    @stages = @deal.pipeline.stages
    if params[:deal][:att_key].present?
      @deal.custom_attributes[params[:deal][:att_key]] = params[:deal][:att_value]
    end

    if Deal::CreateOrUpdate.new(@deal, deal_params).call
      respond_to do |format|
        format.html { redirect_to account_deal_path(current_user.account, @deal) }
        format.turbo_stream
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /deals/1 or /deals/1.json
  def destroy
    @deal.destroy
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to root_path, notice: t('flash_messages.deleted', model: Deal.model_name.human) }
      format.json { head :no_content }
    end
  end

  def events_to_do
    @pagy, @events = pagy(@deal.contact.events.where(deal_id: [nil, @deal.id]).to_do, items: 5)
    respond_to do |format|
      format.turbo_stream
      format.html
    end
  end

  def events_done
    @pagy, @events = pagy(@deal.contact.events.where(deal_id: [nil, @deal.id]).done, items: 5)
    respond_to do |format|
      format.turbo_stream
      format.html
    end
  end

  def deal_products
    @deal_products = @deal.deal_products
  end

  def deal_assignees
    @deal_assignees = @deal.deal_assignees
  end

  def edit_deal_product
  end

  def update_deal_product
    if DealProduct::CreateOrUpdate.new(@deal_product, deal_product_params).call
      respond_to do |format|
        format.html do
          redirect_to deal_products_account_deal_path(current_user.account, @deal_product.deal)
        end
        format.turbo_stream
      end
    else
      render :edit_deal_product, status: :unprocessable_entity
    end
  end

  private

  def set_deal
    @deal = current_user.account.deals.find(params[:id])
  end

  def set_deal_product
    @deal_product = current_user.account.deal_products.find(params[:deal_product_id])
  end

  def deal_product_params
    params.require(:deal_product).permit(*permitted_deal_product_params)
  end

  # Only allow a list of trusted parameters through.
  def deal_params
    params.require(:deal).permit(
      :name, :status, :stage_id, :contact_id, :position,
      contact_attributes: %i[id full_name phone email],
      custom_attributes: {}
    )
  end
end

app/controllers/api/v1/accounts/deals/events_controller.rb
class Api::V1::Accounts::Deals::EventsController < Api::V1::InternalController

  def create
    @deal = @current_user.account.deals.find(params["deal_id"])
    event = @deal.events.new(event_params)
    event.contact = @deal.contact
    event.account = @deal.account
    event.from_me = true

    if event.save
      render json: event, status: :created
    else
      render json: { errors: event.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def event_params
    params.permit(:content, :send_now, :done, :auto_done, :done_at,:title, :scheduled_at, :kind, :app_type, :app_id, custom_attributes: {}, additional_attributes: {})
  end
end

app/controllers/api/v1/accounts/deals_controller.rb
class Api::V1::Accounts::DealsController < Api::V1::InternalController
  def show
    @deal = Deal.find_by_id(params['id'])
    if @deal
      render json: @deal, include: %i[contact stage pipeline], status: :ok
    else
      render json: { errors: 'Not found' }, status: :not_found
    end
  end

  def create
    @deal = DealBuilder.new(current_user, deal_params).perform
    if Deal::CreateOrUpdate.new(@deal, deal_params).call
      render json: @deal, status: :created
    else
      render json: { errors: @deal.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def upsert
    @deal = Deal.where(
      contact_id: params['contact_id']
    ).first_or_initialize

    if Deal::CreateOrUpdate.new(@deal, deal_params).call
      render json: @deal, status: :ok
    else
      render json: { errors: @deal.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def update
    @deal = Deal.find(params['id'])

    if Deal::CreateOrUpdate.new(@deal, deal_params).call
      render json: @deal, status: :ok
    else
      render json: { errors: @deal.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def deal_params
    params.permit(:name, :status, :stage_id, :pipeline_id, :contact_id,
                  contacts_attributes: %i[id full_name phone email], custom_attributes: {})
  end
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/views/accounts/deals/details/_edit.html.erb
<%= turbo_frame_tag dom_id(model, :deal_show_page_overview) do %>
  <%= form_with(model: model, url: update_path) do |form| %>
    <%= form.hidden_field :deal_page_id, value: params[:deal_page_id] %>
    <div class="bg-light-palette-p5">
      <div class="flex items-center py-4 justify-between">
        <div class="flex items-center gap-2 text-dark-gray-palette-p1">
          <i data-lucide=<%= model.class.name.downcase == 'contact' ? 'phone' : 'info' %> class='w-5 h-5 stroke-1.04'></i>
          <p class="typography-body-s-lh150 ">
            <%= t("activerecord.models.#{model.class.name.downcase}.one") %>
          </p>
        </div>
        <div class='flex gap-2'>
          <%= form.submit t('views.accounts.deals.details.edit.save_changes'), class: 'button-default-blank-secondary-sm', data: { turbo_frame: "form_#{model.class.name.downcase}_#{model.id}" } %>
          <%= link_to :back, class: 'button-default-blank-secondary-icon-only-sm' do %>
            <i data-lucide="x"></i>
          <% end %>
        </div>
      </div>
      <div class="mb-4">
        <% if model.errors.any? %>
          <ul class= 'mb-4'>
            <% model.errors.each do |error| %>
              <li class="typography-body-s-lh150 text-auxiliary-palette-red "><%= error.full_message %></li>
            <% end %>
          </ul>
        <% end %>
        <div class='flex flex-col gap-4'>
          <% model.class::FORM_FIELDS.each do | f | %>
            <% unless f.in?([:chatwoot_conversations_label_list, :creator, :total_amount_in_cents]) %>
              <div class="flex flex-col col-span-full gap-2">
                <%= form.label f, class: 'typography-text-s-lh150 text-gray-pallete-p3' %>
                <%= form.text_field f, f == :label_list ? { value: model.labels.join(', '), placeholder: t('views.accounts.deals.details.edit.tag_placeholder'), class: ' form-input !border-light-palette-p3', data: {controller: 'tag-input'} } : { class: "form-input", data: {controller: "input-mask--input-#{f}"} } %>
              </div>
              <% if model.class.name == 'Deal' %>
                <div class="flex flex-col col-span-full gap-2">
                  <%= form.label :stage_id, class: "typography-text-s-lh150 text-gray-pallete-p3" %>
                  <%= form.select(:stage_id, @stages.map { |stage| ["#{stage.pipeline.name} - #{stage.name}", stage.id] }, {}, { class: 'form-input' }) %>
                </div>
              <% end %>
            <% end %>
          <% end %>
          <%= render 'accounts/deals/details/edit_custom_attributes', form: form, model: model %>
        </div>
      </div>
      <div class=" border-t-2 border-light-palette-p3 pb-4 pt-3">
        <div class="flex flex-col gap-2">
          <label class="flex-grow m-0 text-brand-palette-03 typography-text-s-lh150">
            <%= t('views.accounts.deals.details.edit.add_custom_attributes') %>
          </label>
          <div class="w-full">
            <% if model.class.name.downcase == 'deal' %>
              <%= turbo_frame_tag "form_custom_attributes_#{model.class.name.downcase}_#{model.id}" do %>
                <%= link_to account_deal_edit_custom_attributes_path(current_user.account, model), class: 'inline-block w-full h-10 flex justify-center items-center select-none border-2 border-2 bg-light-palette-p4 text-dark-gray-palette-p3 rounded-md border-light-palette-p3 hover:border-brand-palette-06 hover:bg-brand-palette-08 hover:border-2 hover:text-brand-palette-03 hover:duration-100' do %>
                  <i data-lucide="plus" height="18"></i>
                <% end %>
              <% end %>
            <% elsif model.class.name.downcase == 'contact' %>
              <%= turbo_frame_tag "form_custom_attributes_#{model.class.name.downcase}_#{model.id}" do %>
                <%= link_to account_contact_edit_custom_attributes_path(current_user.account, model, deal_page_id: params[:deal_page_id]), class: 'inline-block w-full h-10 flex justify-center items-center select-none border-2 border-2 bg-light-palette-p4 text-dark-gray-palette-p3 rounded-md border-light-palette-p3 hover:border-brand-palette-06 hover:bg-brand-palette-08 hover:border-2 hover:text-brand-palette-03 hover:duration-100' do %>
                  <i data-lucide="plus" height="18"></i>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/accounts/deals/details/_edit_custom_attributes.html.erb
<%= form.fields_for(:custom_attributes) do |sf| %>
  <% model.custom_attributes.each do | custom_attribute | %>
    <div class="flex flex-col gap-2">
      <%= sf.label custom_attribute[0].to_sym, model.custom_attribute_display_name(custom_attribute[0]), class: 'typography-text-s-lh150 text-gray-pallete-p3' %>
      <%= sf.text_field custom_attribute[0].to_sym, value: model.custom_attributes[custom_attribute[0]], class: "form-input" %>
    </div>
  <% end %>
<% end %>

app/views/accounts/deals/details/_show.html.erb
<%= turbo_frame_tag dom_id(model, :deal_show_page_overview) do %>
  <div class="flex items-center py-4 justify-between gap-1.5 relative" data-controller="load-lucid-icons load-flowbite">
    <div class='flex items-center gap-2.5 '>
      <div class="flex items-center gap-2 text-dark-gray-palette-p1">
        <i data-lucide=<%= model.class.name.downcase == 'contact' ? 'phone' : 'info' %> class='w-5 h-5 stroke-1.04'></i>
        <p class="typography-body-s-lh150 ">
          <%= t("activerecord.models.#{model.class.name.downcase}.one") %>
        </p>
      </div>
      <%= render '/components/links/chatwoot_conversation_link', contact: model %>
    </div>
    <div class='flex gap-2'>
      <%= link_to edit_path, class: 'button-default-blank-secondary-icon-only-sm' do %>
        <i data-lucide="pencil"></i>
      <% end %>
      <button type="button" class="button-default-blank-secondary-icon-only-sm" data-accordion-target="#accordion-collapse-<%= "#{model.class.name.downcase}_#{model.id}"%>" aria-expanded="true" aria-controls="accordion-collapse-<%= "#{model.class.name.downcase}_#{model.id}"%> ">
        <i data-accordion-icon data-lucide="chevron-down" class="rotate-180 shrink-0" height="16"></i>
      </button>
    </div>
  </div>
  <div id="accordion-collapse-<%= "#{model.class.name.downcase}_#{model.id}"%>" class="hidden grid sm:grid-cols-2 gap-4 pb-4" aria-labelledby="accordion-collapse-heading-<%= "#{model.class.name.downcase}_#{model.id}"%>">
    <% model.class::SHOW_FIELDS.slice(:deal_page_overview_details).each do | show_field_category |  %>
      <% show_field_category[1].each do | show_field |  %>
        <% if show_field.is_a?(Hash) && show_field.key?(:relations) %>
          <% show_field[:relations].each do |relation_name, field| %>
            <div class="flex flex-col col-span-full">
              <p class='typography-text-s-lh150 text-gray-pallete-p3'>
                <%= t("activerecord.attributes.#{model.model_name.i18n_key}.#{relation_name}") %>
              </p>
              <p class='typography-sub-text-m-lh150 text-dark-gray-palette-p1 break-all'>
                <%= model.send(relation_name)&.send(field) %>
              </p>
            </div>
          <% end %>
        <% else %>
          <% unless show_field.in?([:chatwoot_conversations_label_list]) && model.send(show_field).blank? %>
            <div class="flex flex-col col-span-full">
              <p class='typography-text-s-lh150 text-gray-pallete-p3'>
                <%= t("activerecord.attributes.#{model.model_name.i18n_key}.#{show_field}") %>
              </p>
              <% if show_field.in?([:label_list, :chatwoot_conversations_label_list]) %>
                <%= render 'components/list_labels', labels: model.send(show_field), max_width: '100%', justify_content: 'start' %>
              <% else %>
                <p class='typography-sub-text-m-lh150 text-dark-gray-palette-p1 break-all <%= show_field == :total_amount_in_cents_at_format ? 'stream_deal_total_amount_in_cents' : '' %>'>
                  <%= model.send(show_field) %>
                </p>
              <% end %>
            </div>
          <% end %>
        <% end %>
      <% end %>
      <%= render 'accounts/deals/details/show_custom_attributes', model: model %>
    <% end %>
  </div>
<% end %>

app/views/accounts/deals/details/_show_custom_attributes.html.erb
<% model.custom_attributes.each do | custom_attribute | %>
  <div class="flex flex-col col-span-full">
    <label class="typography-text-s-lh150 text-gray-pallete-p3">
      <%= model.custom_attribute_display_name(custom_attribute[0]) %>
    </label>
    <p class="typography-sub-text-m-lh150 text-dark-gray-palette-p1">
      <%= custom_attribute[1] %>
    </p>
  </div>
<% end %>