config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Motor::Admin => '/motor_admin'
  mount Sidekiq::Web => '/sidekiq'
  mount GoodJob::Engine => 'good_job'

  draw(:installation)

  resources :accounts, module: :accounts do
    resources :webpush_subscriptions, only: [:create]
    resources :settings, only: [:index]
    resources :welcome, only: [:index]
    resources :custom_attributes_definitions, module: :settings do
    end

    resources :webhooks, module: :settings do
    end

    resources :users do
      get 'select_user_search', on: :collection
    end
    resources :products do
      get 'edit_custom_attributes', on: :member
      patch 'update_custom_attributes', on: :member
      get 'select_product_search', on: :collection
    end
    resources :contacts do
      get 'search', to: 'contacts#search', on: :collection
      get 'edit_custom_attributes'
      get 'chatwoot_conversation_link', on: :member
      patch 'update_custom_attributes'
      get 'select_contact_search', on: :collection
      resources :events, module: :contacts do
      end
      namespace :events, module: :contacts do
        namespace :apps, module: :events do
        end
      end

      collection do
        resources :chatwoot_embed, only: %i[show new create], controller: 'contacts/chatwoot_embed' do
          post 'search', on: :collection
        end
      end
      get 'hovercard_preview', on: :member
    end
    resources :pipelines do
      get 'import'
      post 'import_file'
      get 'export'
      member do
        get 'new_bulk_action'
        get 'bulk_action'
        post 'create_bulk_action'
      end
    end

    resources :deals do
      patch 'update_deal_product', on: :member
      get 'edit_deal_product', on: :member
      get 'deal_products', on: :member
      get 'deal_assignees', on: :member
      get 'events_to_do', on: :member
      get 'events_done', on: :member
      get 'add_contact'
      post 'commit_add_contact'
      delete 'remove_contact'
      get 'new_select_contact', on: :collection
      get 'edit_custom_attributes'
      patch 'update_custom_attributes'
    end
    resources :deal_products, only: %i[destroy new create]
    resources :deal_assignees, only: %i[destroy new create]

    namespace :apps do
      resources :evolution_apis do
        member do
          get 'pair_qr_code'
          post 'refresh_qr_code'
        end
      end
      resources :chatwoots
      # resources :events, module: :contacts
      resource :ai_assistent, only: %i[edit update]
    end
    resources :attachments, only: [:destroy]
    resources :stages, only: [:show]
  end
  if ENV.fetch('ENABLE_USER_SIGNUP', 'false') == 'true'
    devise_for :users, controllers: {
      registrations: 'users/registrations'
    }
  else
    devise_for :users, skip: [:registrations]
  end

  root to: 'accounts/pipelines#index'

  namespace :api do
    namespace :v1 do
      resources :accounts, module: :accounts do
        resources :deals, only: %i[show create update] do
          post 'upsert', on: :collection
          resources :events, only: [:create], module: :deals do
          end
        end
        resources :contacts, only: %i[show create] do
          post 'upsert', on: :collection
          match 'search', on: :collection, via: %i[get post]
        end
        namespace :apps do
          # resources :events, module: :contacts
        end
        resources :deal_products, only: %i[create show]
        resources :products, only: %i[create show] do
          match 'search', on: :collection, via: %i[get post]
        end
      end

      resources :contacts, only: [:create] do
      end
    end
  end

  namespace :embedded do
    resources :accounts, module: :accounts do
      namespace :apps do
        resources :chatwoots, only: [:index] do
        end
      end
    end
  end

  namespace :apps do
    resources :chatwoots do
      collection do
        post 'webhooks'
        get 'embedding'
        get 'embedding_init_authenticate'
        post 'embedding_authenticate'
      end
    end
    resources :evolution_apis do
      collection do
        post 'webhooks'
      end
    end
  end
  get 'service-worker' => 'pwa#service_worker'
  get 'webmanifest' => 'pwa#manifest'
end

app/views/layouts/shared/_analytics_scripts_body.html.erb
<% if ENV.fetch('COUNTLY_ENDPOINT', nil).present? && ENV.fetch('COUNTLY_KEY', nil).present? %>
  <noscript><img src='<%= ENV.fetch('COUNTLY_ENDPOINT', nil) %>/pixel.png?app_key=<%= ENV.fetch('COUNTLY_KEY', nil) %>&begin_session=1'/></noscript>
<% end %>

app/views/layouts/shared/_navbar.html.erb
<% if controller_path == 'accounts/pipelines' && ['index', 'show', 'edit', 'new'].include?(action_name) %>
  <%= render "layouts/shared/navbar_pipe" %>
<% elsif controller_path == 'accounts/deals' && ['show'].include?(action_name) %>
  <%= render "layouts/shared/navbar_show_deal" %>
<% elsif controller_path == 'accounts/deals' && ['show'].exclude?(action_name) %>
  <%= render "layouts/shared/navbar_deal" %>
<% elsif controller_path == 'accounts/contacts' %>
  <%= render "layouts/shared/navbar_contact" %>
<% elsif controller_path == 'accounts/settings' %>
  <%= render "layouts/shared/navbar_setting" %>
<% elsif controller_path == 'accounts/settings/custom_attributes_definitions'  %>
  <%= render "layouts/shared/navbar_custom_attributes_definitions" %>
<% elsif controller_path == 'accounts/apps/chatwoots'  %>
  <%= render "layouts/shared/navbar_chatwoot" %>
<% elsif controller_path == "accounts/settings/webhooks"  %>
  <%= render "layouts/shared/navbar_webhook" %>
<% elsif controller_path == 'accounts/users'  %>
  <%= render "layouts/shared/navbar_users" %>
<% elsif controller_path == 'accounts/apps/evolution_apis'  %>
  <%= render "layouts/shared/navbar_evolution_api" %>
<% elsif controller_path == 'accounts/products'  %>
  <%= render "layouts/shared/navbar_product" %>
<% end %>

app/views/layouts/shared/_navbar_custom_attributes_definitions.html.erb
<nav class="navbar-container">
  <% if controller_path == 'accounts/settings/custom_attributes_definitions' && ['index', 'show'].include?(action_name) %>
    <h1 class="typography-title-b-lh150 text-dark-gray-palette-p1">
      <%= t('activerecord.models.custom_attribute_definition.other') %>
    </h1>
  <% else %>
    <h1 class="typography-title-b-lh150 text-dark-gray-palette-p1">
      <%= t('activerecord.models.custom_attribute_definition.new') %>
    </h1>
  <% end%>
</nav>

app/views/layouts/shared/_navbar_deal.html.erb
<nav class="navbar-container">
  <% if ['index'].include?(action_name) %>
    <h1 class="typography-title-b-lh150 text-dark-gray-palette-p1">
      <%= t('activerecord.models.deal.other') %>
    </h1>
    <div class='flex items-center gap-4'>
      <% if @first_pipeline %>
        <%= link_to account_pipeline_path(Current.account, @first_pipeline),
        class: 'button-default-blank-secondary-icon-only-md', data: { tooltip_target: "tooltip-deal-kanban-link" } do %>
          <i data-lucide="kanban"></i>
        <% end %>
        <div id="tooltip-deal-kanban-link" role="tooltip" class="absolute z-10 invisible inline-block px-3 py-2 text-sm font-medium text-white transition-opacity duration-300 bg-gray-900 rounded-lg shadow-xs opacity-0 tooltip dark:bg-gray-700">
          <%= t('activerecord.models.deal.kanban_mode') %>
          <div class="tooltip-arrow" data-popper-arrow></div>
        </div>
      <% end %>
      <%= render 'components/navbar/user_menu' %>
    </div>
  <% else ['new'].include?(action_name) %>
    <h1 class="typography-title-b-lh150 text-dark-gray-palette-p1">
      <%= t('activerecord.models.deal.new') %>
    </h1>
  <% end %>
</nav>

app/views/layouts/shared/_navbar_pipe.html.erb
<% if ['edit'].include?(action_name) %>
  <nav class="navbar-container">
    <h1 class="typography-title-b-lh150 text-dark-gray-palette-p1">
      <%= t('activerecord.models.pipeline.edit') %>
    </h1>
  </nav>
<% elsif ['new'].include?(action_name) %>
  <nav class="navbar-container">
    <h1 class="typography-title-b-lh150 text-dark-gray-palette-p1">
      <%= t('activerecord.models.pipeline.new') %>
    </h1>
  </nav>
<% else %>
  <nav class="bg-light-palette-p5 px-6 py-2 sm:py-4 sm:px-4 md:px-8  border-b-2 border-light-palette-p3">
    <div class="flex flex-wrap gap-4 items-center justify-end sm:justify-between">
      <div class="flex items-center sm:order-2 space-x-3 sm:space-x-0 justify-end rtl:space-x-reverse">
        <%= render 'components/navbar/user_menu' %>
        <button data-collapse-toggle="navbar-user" type="button" class="button-default-outline-secondary-md-icon-only-md sm:hidden" aria-controls="navbar-user" aria-expanded="false">
          <span class="sr-only">Open main menu</span>
          <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
          </svg>
        </button>
      </div>
      <div class="items-center justify-between hidden w-full sm:flex sm:w-auto sm:order-1" id="navbar-user">
        <div class="flex flex-col pb-4 gap-2 sm:pb-0 rounded-lg sm:gap-4 rtl:space-x-reverse sm:flex-row sm:mt-0 sm:border-0 sm:bg-white ">
          <div class="flex flex-wrap flex-1 h-10 shrink-0">
            <div class="h-10 w-10 flex items-center justify-center border-solid border-2 border-light-palette-p3 rounded-l-md bg-brand-palette-08">
              <%= embedded_svg('vectooor2.svg', { class: 'h-5 w-5 fill-brand-palette-03' }) %>
            </div>
            <select class="px-2.5 h-10 mx-[-2px] border-solid border-2 border-light-palette-p3 flex-1 sm:flex-none sm:w-40 md:w-52 hover:border-light-palette-p2 hover:z-10 hover:cursor-pointer focus:border-light-palette-p2 focus:ring-0 hover:text-brand-palette-04 focus:z-10 typography-text-r-lh150 text-dark-gray-palette-p3 truncate" onchange="window.location=this.value">
              <% @pipelines.each do |pipeline| %>
                <option value="<%= account_pipeline_path(Current.account, pipeline.id) %>" <%= pipeline.id == @pipeline.id ? 'selected' : '' %>>
                  <%= pipeline.name %>
                </option>
                <% end %>
              </select>
              <%= link_to edit_account_pipeline_path(Current.account, @pipeline), class:'h-10 w-10 flex items-center justify-center border-solid border-2 border-light-palette-p3 rounded-r-lg sm:flex-1 hover:border-light-palette-p2' do %>
                <%= embedded_svg('pencil-icon.svg') %>
              <% end %>
            </div>
            <div id="tooltip-new-deal-link" role="tooltip" class="hidden sm:inline-block lg:hidden absolute z-10 invisible px-3 py-2 text-sm font-medium text-white transition-opacity duration-300 bg-gray-900 rounded-lg shadow-xs opacity-0 tooltip dark:bg-gray-700">
              <%= t('activerecord.models.deal.new') %>
              <div class="tooltip-arrow" data-popper-arrow></div>
            </div>
            <%= link_to new_select_contact_account_deals_path(Current.account), class: 'button-default-fill-primary-md', data: {tooltip_target: 'tooltip-new-deal-link'} do %>
              <i data-lucide="clipboard-plus"></i>
              <p class="block sm:hidden lg:block">
                <%= t('activerecord.models.deal.new') %>
              </p>
            <% end %>
            <div id="tooltip-new-pipeline-link" role="tooltip" class="hidden sm:inline-block lg:hidden absolute z-10 invisible px-3 py-2 text-sm font-medium text-white transition-opacity duration-300 bg-gray-900 rounded-lg shadow-xs opacity-0 tooltip dark:bg-gray-700">
              <%= t('activerecord.models.pipeline.new') %>
              <div class="tooltip-arrow" data-popper-arrow></div>
            </div>
            <%= link_to new_account_pipeline_path(Current.account), class: 'button-default-blank-secondary-md', data: {tooltip_target: 'tooltip-new-pipeline-link'} do %>
              <i data-lucide="funnel-plus"></i>
              <p class="block sm:hidden lg:block">
                <%= t('activerecord.models.pipeline.new') %>
              </p>
            <% end %>
            <div id="tooltip-filter-deal" role="tooltip" class="hidden absolute z-10 invisible sm:inline-block px-3 py-2 text-sm font-medium text-white transition-opacity duration-300 bg-gray-900 rounded-lg shadow-xs opacity-0 tooltip dark:bg-gray-700">
              <%= t('activerecord.models.filter', model: Deal.model_name.human.pluralize) %>
              <div class="tooltip-arrow" data-popper-arrow></div>
            </div>
            <div data-controller="filter-select-status-deal" class='w-full sm:w-auto'>
              <button id="dropdownSortDeals" data-dropdown-toggle="dropdownSort" class="button-default-blank-secondary-md aria-selected:button-default-fill-primary-md w-full sm:auto" type="button" aria-selected="false" data-filter-select-status-deal-target="button" data-tooltip-target='tooltip-filter-deal'>
                <i data-lucide="sliders-horizontal"></i>
                <p class="block sm:hidden">
                  <%= t('activerecord.models.filter', model: Deal.model_name.human.pluralize) %>
                </p>
              </button>
              <%= form_with(url: account_pipeline_path(Current.account, @pipeline),method: :get,data: {turbo_frame: :stages, 'filter-select-status-deal-target': 'form', turbo_action: 'advance' } ) do |form| %>
                <%= hidden_field_tag "filter_status_deal", nil, data: { 'filter-select-status-deal-target': 'status' } %>
                <div id="dropdownSort" class="z-10 hidden bg-white divide-y divide-gray-300 rounded-lg shadow w-64 dark:bg-gray-700 dark:divide-gray-600">
                  <ul class="py-2 typography-text-m-lh150 text-dark-gray-palette-p3 dark:text-gray-200" aria-labelledby="dropdownDefaultButton" data-filter-select-status-deal-target="links" >
                    <li>
                      <%= link_to "", data: { action: "click->filter-select-status-deal#select" }, class: "flex items-center space-x-2 px-4 py-2 hover:bg-gray-300 dark:hover:bg-gray-600 hover:text-dark-gray-palette-p1 dark:hover:text-white aria-selected:bg-brand-palette-07 aria-selected:text-brand-palette-03 aria-selected:pointer-events-none", value: "", 'aria-selected': 'false' do %>
                        <i data-lucide="copy-plus"></i>
                        <p><%= t('views.layouts.shared.navbar_pipe.all_open_deals') %></p>
                      <% end %>
                    </li>
                    <li>
                      <%= link_to "", data: { action: "click->filter-select-status-deal#select" }, class: "flex items-center space-x-2 px-4 py-2 hover:bg-gray-300 dark:hover:bg-gray-600 hover:text-dark-gray-palette-p1 dark:hover:text-white aria-selected:bg-brand-palette-07 aria-selected:text-brand-palette-03 aria-selected:pointer-events-none", value: "won", 'aria-selected': 'false' do %>
                        <i data-lucide="copy-check"></i>
                        <p><%= t('views.layouts.shared.navbar_pipe.all_won_deals') %></p>
                      <% end %>
                    </li>
                    <li>
                      <%= link_to "", data: { action: "click->filter-select-status-deal#select" }, class: "flex items-center space-x-2 px-4 py-2 hover:bg-gray-300 dark:hover:bg-gray-600 hover:text-dark-gray-palette-p1 dark:hover:text-white aria-selected:bg-brand-palette-07 aria-selected:text-brand-palette-03 aria-selected:pointer-events-none", value: "lost", 'aria-selected': 'false' do %>
                        <i data-lucide="copy-x"></i>
                        <p><%= t('views.layouts.shared.navbar_pipe.all_lost_deals') %></p>
                      <% end %>
                    </li>
                    <li>
                      <%= link_to "", data: { action: "click->filter-select-status-deal#select" }, class: "flex items-center space-x-2 px-4 py-2 hover:bg-gray-300 dark:hover:bg-gray-600 hover:text-dark-gray-palette-p1 dark:hover:text-white aria-selected:bg-brand-palette-07 aria-selected:text-brand-palette-03 aria-selected:pointer-events-none", value: "all", 'aria-selected': 'false' do %>
                        <i data-lucide="copy"></i>
                        <p><%= t('views.layouts.shared.navbar_pipe.all_deals') %></p>
                      <% end %>
                    </li>
                  </ul>
                </div>
              <% end %>
            </div>
            <div id="tooltip-deal-list-link" role="tooltip" class="hidden absolute z-10 invisible sm:inline-block px-3 py-2 text-sm font-medium text-white transition-opacity duration-300 bg-gray-900 rounded-lg shadow-xs opacity-0 tooltip dark:bg-gray-700">
              <%= t('activerecord.models.deal.list_mode') %>
              <div class="tooltip-arrow" data-popper-arrow></div>
            </div>
            <%= link_to account_deals_path(Current.account), class: 'button-default-blank-secondary-md', data: { tooltip_target: "tooltip-deal-list-link" } do %>
              <i data-lucide="list"></i>
              <p class="block sm:hidden">
                <%= t('activerecord.models.deal.list_mode') %>
              </p>
            <% end %>
            <div id="tooltip-deal-list-link" role="tooltip" class="absolute z-10 invisible inline-block px-3 py-2 text-sm font-medium text-white transition-opacity duration-300 bg-gray-900 rounded-lg shadow-xs opacity-0 tooltip dark:bg-gray-700">
              <%= t('activerecord.models.deal.list_mode') %>
              <div class="tooltip-arrow" data-popper-arrow></div>
            </div>
          </div>
        </div>
      </div>
    </nav>
  <% end %>

app/views/layouts/shared/_navbar_show_deal.html.erb
<nav class="navbar-container" id='navbar_deal' data-controller='load-lucid-icons'>
  <div class="flex items-center">
    <%= link_to(account_pipeline_path(current_user.account, @deal.pipeline), class: "flex border-solid border-2 border-light-palette-p3 rounded-md hover:bg-brand-palette-08 focus:bg-brand-palette-08 p-1.5") do %>
      <i data-lucide="chevron-left"></i>
    <% end %>
    <div class="pl-4 lg:flex lg:items-center">
      <div class="h-full lg:border-r-2 border-light-palette-p3 lg:px-6 xl:px-16">
        <p class="typography-body-s-lh150 text-dark-gray-palette-p1"><%= @deal.name %></p>
      </div>
      <div class="flex items-center h-5">
        <div class=" flex items-center mr-[13px] lg:pl-6 xl:pl-16">
          <p class="m-0 p-0 typography-text-m-lh150 text-dark-gray-palette-p3"><%= @deal.stage.pipeline.name %></p>
        </div>
        <div class=" flex items-center mx-1.5 lg:mx-3 ">
          <i data-lucide="chevron-right" class="stroke-dark-gray-palette-p3"></i>
        </div>
        <div class=" flex items-center ml-1.5 lg:mx-3">
          <p class="m-0 typography-text-m-lh150 text-dark-gray-palette-p3"><%= @deal.stage.name %></p>
        </div>
      </div>
    </div>
  </div>
  <div class="hidden sm:flex gap-2">
    <% if @deal.open? %>
      <%= link_to(
    t('views.layouts.shared.navbar_deal.delete'),
    account_deal_path(current_user.account, @deal, format: :html),
    method: :delete,
    data: { confirm: t('views.layouts.shared.navbar_deal.are_you_sure?'),
    turbo: false },
    class: 'btn-secondary') %>
      <%= link_to(
    t('views.layouts.shared.navbar_deal.lost'),
    account_deal_path(current_user.account, @deal, deal: { status: 'lost'} ),
    method: :patch,
    data: { confirm: t('views.layouts.shared.navbar_deal.are_you_sure?') },
    class: 'deal-lost-btn') %>
      <%= link_to(
    t('views.layouts.shared.navbar_deal.won'),
    account_deal_path(current_user.account, @deal, deal: { status: 'won'}),
    method: :patch,
    data: { confirm: t('views.layouts.shared.navbar_deal.are_you_sure?') },
    class: 'deal-won-btn') %>
    <% else %>
      <div class="deal-<%= @deal.status %>-btn pointer-events-none"><%= t("views.layouts.shared.navbar_deal.deal_#{@deal.status}") %></div>
      <%= link_to(
    t('views.layouts.shared.navbar_deal.reopen'),
    account_deal_path(current_user.account, @deal, deal: { status: 'open'} ),
    method: :patch,
    data: { confirm: t('views.layouts.shared.navbar_deal.are_you_sure?') },
    class: 'btn-primary') %>
      <%= link_to(
    t('views.layouts.shared.navbar_deal.delete'),
    account_deal_path(current_user.account, @deal),
    method: :delete,
    data: { confirm: t('views.layouts.shared.navbar_deal.are_you_sure?') },
    class: 'btn-secondary') %>
    <% end %>
  </div>
</nav>

app/views/layouts/shared/_navbar_users.html.erb
<nav class="navbar-container">
  <% if ['new'].include?(action_name) %>
    <h1 class="typography-title-b-lh150 text-dark-gray-palette-p1">
      <%= t('activerecord.models.contact.new') %>
    </h1>
  <% elsif ['edit'].include?(action_name) %>
    <h1 class="typography-title-b-lh150 text-dark-gray-palette-p1">
      <%= t('activerecord.models.contact.edit') %>
    </h1>
  <% else %>
    <h1 class="typography-title-b-lh150 text-dark-gray-palette-p1">
      <%= t('activerecord.models.user.other') %>
    </h1>
    <%= link_to t('activerecord.models.user.new'), new_account_user_path(current_user.account), class: 'btn-secondary'%>
  <% end %>
</nav>

app/views/layouts/shared/_navbar_webhook.html.erb
<nav class="navbar-container">
  <% if ['new'].include?(action_name) %>
    <h1 class="typography-title-b-lh150 text-dark-gray-palette-p1">
      <%= t('activerecord.models.webhook.one') %>
    </h1>
  <% else%>
    <h1 class="typography-title-b-lh150 text-dark-gray-palette-p1">
      <%= t('activerecord.models.webhook.other') %>
    </h1>
    <%= link_to new_account_webhook_path(current_user.account), class: 'btn-secondary' do %>
      <%= t('activerecord.models.webhook.new') %>
    <% end %>
  <% end%>
</nav>

app/views/layouts/shared/_sidebar.html.erb
<div data-controller="element-expanded" aria-expanded="true" class="group ease-in duration-300 h-screen border-r-2 border-light-palette-p3 bg-light-palette-p5 relative p-4 space-y-4 w-[72px] aria-expanded:w-60" id="element-expand" data-element-expanded-target='sidebar'>
  <div class="flex items-center flex-wrap justify-between">
    <%= link_to(root_path()) do %>
      <%= image_tag "logo.svg", class: 'w-36 block group-aria-[expanded=false]:hidden' %>
    <% end %>
    <%= link_to(root_path()) do %>
      <div  class= 'hidden group-aria-[expanded=false]:block w-[40px] border-2 border-light-palette-p3 p-1.5 rounded-md hover:bg-brand-palette-08' >
        <%= image_tag "logo-patinha.svg"%>
      </div>
    <% end %>
    <button data-action="click->element-expanded#toggle" class="group-aria-[expanded=false]:mt-4 group-aria-[expanded=false]:h-[40px] group-aria-[expanded=false]:p-2 border-2 mt-0 h-auto border-light-palette-p3 p-2.5 rounded-md hover:bg-brand-palette-08"><i data-lucide="menu" class="w-5 stroke-dark-gray-palette-p3"></i></button>
  </div>
  <div class="hidden group-aria-[expanded=false]:block h-[2px] w-full bg-light-palette-p3"></div>
  <ul class="flex flex-col space-y-3 border-b-md">
    <li class="<%= ' bg-brand-palette-08  !border-brand-palette-07 rounded-md !text-brand-palette-03' if request.path.include?('pipelines') or request.path.include?('deal') %> text-dark-gray-palette-p3 border-2 border-transparent hover:bg-brand-palette-08 hover:rounded-md group-aria-[expanded=false]:w-full group-aria-[expanded=false]:h-[40px]">
      <%= link_to(account_pipelines_path(Current.account), class: 'group-aria-[expanded=false]:p-2.5 flex space-x-3 p-3 items-center') do %>
        <%= embedded_svg("deals-icon.svg", class: "w-4 #{'!fill-brand-palette-03 ' if request.path.include?('pipelines') or request.path.include?('deal')} group-aria-[expanded=false]:mx-auto fill-dark-gray-palette-p3") %>
        <span class="group-aria-[expanded=false]:hidden inline-block ml-2 typography-text-m-lh150">
          <%= t('activerecord.models.deal.one') %>
        </span>
      <% end %>
    </li>
    <li class="<%= ' bg-brand-palette-08 !border-brand-palette-07 rounded-md !text-brand-palette-03' if request.path.include?('contact') %> text-dark-gray-palette-p3 border-2 border-transparent hover:bg-brand-palette-08 hover:rounded-md group-aria-[expanded=false]:w-full group-aria-[expanded=false]:h-[40px]">
      <%= link_to(account_contacts_path(Current.account), class: 'group-aria-[expanded=false]:p-2.5 flex space-x-3 p-3 items-center') do %>
        <%= embedded_svg("contacts-icon.svg", class: "w-4 #{'!fill-brand-palette-03 ' if request.path.include?('contact') or request.path.include?('contact')} group-aria-[expanded=false]:mx-auto fill-dark-gray-palette-p3") %>
        <span class="group-aria-[expanded=false]:hidden inline-block ml-2 typography-text-m-lh150">
          <%= t('activerecord.models.contact.one') %>
        </span>
      <% end %>
    </li>
    <li class="<%= ' bg-brand-palette-08 !border-brand-palette-07 rounded-md !text-brand-palette-03' if request.path.include?('product') %> text-dark-gray-palette-p3 border-2 border-transparent hover:bg-brand-palette-08 hover:rounded-md group-aria-[expanded=false]:w-full group-aria-[expanded=false]:h-[40px]">
      <%= link_to(account_products_path(Current.account), class: 'group-aria-[expanded=false]:p-2 flex space-x-3 p-3 items-center') do %>
        <i data-lucide="box" class="w-[18px] h-[18px] <%= '!stroke-brand-palette-03 ' if request.path.include?('product') %> group-aria-[expanded=false]:mx-auto stroke-dark-gray-palette-p3" ></i>
        <span class="group-aria-[expanded=false]:hidden inline-block ml-2 typography-text-m-lh150">
          <%= t('activerecord.models.product.one') %>
        </span>
      <% end %>
    </li>
    <div class="h-[2px] w-full bg-light-palette-p3"></div>
    <li class="<%= 'bg-brand-palette-08 !border-brand-palette-07 rounded-md !text-brand-palette-03' if request.path.include?('settings') %> text-dark-gray-palette-p3 border-2 border-transparent icons-button-sidebar mt-auto  absolute bottom-4 right-3 left-3 hover:bg-brand-palette-08 hover:rounded-md">
      <%= link_to(account_settings_path(Current.account), class: 'icons-link-sidebar flex space-x-3 p-3 items-center') do %>
        <%= embedded_svg("company-icon.svg", class: "w-4 lg:m-0 flex #{'!fill-brand-palette-03 ' if request.path.include?('settings')} group-aria-[expanded=false]:mx-auto fill-dark-gray-palette-p3") %>
        <span class="group-aria-[expanded=false]:hidden inline-block ml-2 typography-text-m-lh150">
          <%= t('views.layouts.shared.sidebar.company') %>
        </span>
      <% end %>
    </li>
  </ul>
</div>