config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Motor::Admin => '/motor_admin'
  mount Sidekiq::Web => '/sidekiq'
  mount GoodJob::Engine => 'good_job'

  draw(:installation)

  resources :accounts, module: :accounts do
    resources :webpush_subscriptions, only: [:create]
    resources :settings, only: [:index]
    resources :welcome, only: [:index]
    resources :custom_attributes_definitions, module: :settings do
    end

    resources :webhooks, module: :settings do
    end

    resources :users do
      get 'select_user_search', on: :collection
    end
    resources :products do
      get 'edit_custom_attributes', on: :member
      patch 'update_custom_attributes', on: :member
      get 'select_product_search', on: :collection
    end
    resources :contacts do
      get 'search', to: 'contacts#search', on: :collection
      get 'edit_custom_attributes'
      get 'chatwoot_conversation_link', on: :member
      patch 'update_custom_attributes'
      get 'select_contact_search', on: :collection
      resources :events, module: :contacts do
      end
      namespace :events, module: :contacts do
        namespace :apps, module: :events do
        end
      end

      collection do
        resources :chatwoot_embed, only: %i[show new create], controller: 'contacts/chatwoot_embed' do
          post 'search', on: :collection
        end
      end
      get 'hovercard_preview', on: :member
    end
    resources :pipelines do
      get 'import'
      post 'import_file'
      get 'export'
      member do
        get 'new_bulk_action'
        get 'bulk_action'
        post 'create_bulk_action'
      end
    end

    resources :deals do
      patch 'update_deal_product', on: :member
      get 'edit_deal_product', on: :member
      get 'deal_products', on: :member
      get 'deal_assignees', on: :member
      get 'events_to_do', on: :member
      get 'events_done', on: :member
      get 'add_contact'
      post 'commit_add_contact'
      delete 'remove_contact'
      get 'new_select_contact', on: :collection
      get 'edit_custom_attributes'
      patch 'update_custom_attributes'
    end
    resources :deal_products, only: %i[destroy new create]
    resources :deal_assignees, only: %i[destroy new create]

    namespace :apps do
      resources :evolution_apis do
        member do
          get 'pair_qr_code'
          post 'refresh_qr_code'
        end
      end
      resources :chatwoots
      # resources :events, module: :contacts
      resource :ai_assistent, only: %i[edit update]
    end
    resources :attachments, only: [:destroy]
    resources :stages, only: [:show]
  end
  if ENV.fetch('ENABLE_USER_SIGNUP', 'false') == 'true'
    devise_for :users, controllers: {
      registrations: 'users/registrations'
    }
  else
    devise_for :users, skip: [:registrations]
  end

  root to: 'accounts/pipelines#index'

  namespace :api do
    namespace :v1 do
      resources :accounts, module: :accounts do
        resources :deals, only: %i[show create update] do
          post 'upsert', on: :collection
          resources :events, only: [:create], module: :deals do
          end
        end
        resources :contacts, only: %i[show create] do
          post 'upsert', on: :collection
          match 'search', on: :collection, via: %i[get post]
        end
        namespace :apps do
          # resources :events, module: :contacts
        end
        resources :deal_products, only: %i[create show]
        resources :products, only: %i[create show] do
          match 'search', on: :collection, via: %i[get post]
        end
      end

      resources :contacts, only: [:create] do
      end
    end
  end

  namespace :embedded do
    resources :accounts, module: :accounts do
      namespace :apps do
        resources :chatwoots, only: [:index] do
        end
      end
    end
  end

  namespace :apps do
    resources :chatwoots do
      collection do
        post 'webhooks'
        get 'embedding'
        get 'embedding_init_authenticate'
        post 'embedding_authenticate'
      end
    end
    resources :evolution_apis do
      collection do
        post 'webhooks'
      end
    end
  end
  get 'service-worker' => 'pwa#service_worker'
  get 'webmanifest' => 'pwa#manifest'
end

app/controllers/accounts/apps/ai_assistents_controller.rb
# frozen_string_literal: true

class Accounts::Apps::AiAssistentsController < InternalController
  before_action :set_ai_assistent

  def edit; end

  def update
    if @ai_assistent.update(ai_assistent_params)
      redirect_to edit_account_apps_ai_assistent_path(current_user.account),
                  notice: t('flash_messages.updated', model: Apps::AiAssistent.model_name.human)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_ai_assistent
    @ai_assistent = Apps::AiAssistent.first.presence || Apps::AiAssistent.create
  end

  def ai_assistent_params
    params.require(:apps_ai_assistent).permit(:auto_reply, :model, :api_key, :enabled)
  end
end

app/controllers/accounts/apps/chatwoots_controller.rb
class Accounts::Apps::ChatwootsController < InternalController
  before_action :set_chatwoot, only: %i[edit update destroy]

  def new
    if current_user.account.apps_chatwoots.blank?
      @chatwoot = current_user.account.apps_chatwoots.new
    else
      redirect_to edit_account_apps_chatwoot_path(current_user.account, current_user.account.apps_chatwoots.first)
    end
  end

  def edit; end

  def create
    result = Accounts::Apps::Chatwoots::Create.call(current_user.account, chatwoot_params)
    @chatwoot = result[result.keys.first]
    if result.key?(:ok)
      redirect_to edit_account_apps_chatwoot_path(current_user.account, @chatwoot),
                  notice: t('flash_messages.created', model: Apps::Chatwoot.model_name.human)
    else
      render :new
    end
  end

  def destroy
    result = Accounts::Apps::Chatwoots::Delete.call(current_user.account, @chatwoot)
    if result.key?(:ok)
      redirect_to account_settings_path(current_user.account),
                  notice: t('flash_messages.deleted', model: Apps::Chatwoot.model_name.human)
    end
  end

  def update
    @chatwoot.update(chatwoot_params)
    redirect_to edit_account_apps_chatwoot_path(current_user.account, current_user.account.apps_chatwoots.first)
  end

  private

  def set_chatwoot
    @chatwoot = current_user.account.apps_chatwoots.first
  end

  def chatwoot_params
    params.require(:apps_chatwoot).permit(:chatwoot_endpoint_url, :chatwoot_account_id, :chatwoot_user_token, :active)
  end
end

app/controllers/accounts/apps/evolution_apis_controller.rb
class Accounts::Apps::EvolutionApisController < InternalController
  before_action :set_evolution_api, only: %i[edit update refresh_qr_code pair_qr_code destroy]

  def new
    @evolution_api = Apps::EvolutionApi.new
  end

  def create
    result = Accounts::Apps::EvolutionApis::Create.call(current_user, evolution_api_params)
    @evolution_api = result[result.keys.first]
    if result.key?(:ok)
      redirect_to pair_qr_code_account_apps_evolution_api_path(current_user.account, @evolution_api.id)
    else
      @evolution_api = result[:error]
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @evolution_apis = current_user.account.apps_evolution_apis.order(updated_at: :desc)
    @pagy, @evolution_apis = pagy(@evolution_apis)
  end

  def edit; end

  def update
    if @evolution_api.update(evolution_api_params)
      flash[:notice] = t('flash_messages.updated', model: Apps::EvolutionApi.model_name.human)
      redirect_to edit_account_apps_evolution_api_path(current_user.account, @evolution_api)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def refresh_qr_code
    @evolution_api.update({
                            instance: @evolution_api.generate_token('instance'),
                            token: @evolution_api.generate_token('token')
                          })

    Accounts::Apps::EvolutionApis::Instance::Create.call(@evolution_api)
  end

  def destroy
    if @evolution_api.destroy
      respond_to do |format|
        format.html do
          redirect_to account_apps_evolution_apis_path(current_user.account),
                      notice: t('flash_messages.deleted', model: Apps::EvolutionApi.model_name.human)
        end
        format.turbo_stream
      end
    end
  end

  def pair_qr_code; end

  private

  def set_evolution_api
    @evolution_api = current_user.account.apps_evolution_apis.find(params[:id])
  end

  def evolution_api_params
    params.require(:apps_evolution_api).permit(:name)
  end
end

app/controllers/accounts/apps_controller.rb
class Accounts::AppsController < InternalController
  before_action :set_contact, only: %i[show edit update destroy]

  # GET /contacts or /contacts.json
  def index
    @apps = current_user.account.apps
    @pagy, @apps = pagy(@apps)
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit; end

  # POST /contacts or /contacts.json
  def create
    @contact = current_user.account.contacts.new(contact_params)

    if @contact.save
      redirect_to account_contact_path(current_user.account, @contact),
                  notice: t('flash_messages.created', model: Contact.model_name.human)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        redirect_to account_contact_path(current_user.account, @contact),
                    notice: t('flash_messages.updated', model: Contact.model_name.human)
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html do
        redirect_to contacts_url, notice: t('flash_messages.deleted', model: Contact.model_name.human)
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_contact
    @contact = Contact.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def contact_params
    params.require(:contact).permit(:full_name, :phone, :email, custom_attributes: {})
  end
end

app/controllers/accounts/attachments_controller.rb
class Accounts::AttachmentsController < InternalController
  before_action :set_attachment, only: %i[destroy]

  def destroy
    @attachment.destroy
    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  def set_attachment
    @attachment = Attachment.find(params[:id])
  end
end

app/controllers/accounts/contacts/chatwoot_embed_controller.rb
class Accounts::Contacts::ChatwootEmbedController < InternalController
  layout 'embed'
  before_action :set_contact, only: %i[show]

  def search
    contact = contact_search

    if contact.present?
      redirect_to account_chatwoot_embed_path(current_user.account, contact)
    else
      chatwoot_contact = JSON.parse(params['chatwoot_contact'])
      @contact = current_user.account.contacts.new({
                                                     full_name: chatwoot_contact['name'],
                                                     email: chatwoot_contact['email'],
                                                     phone: chatwoot_contact['phone_number'],
                                                     additional_attributes: { 'chatwoot_id': chatwoot_contact['id'] }
                                                   })
      render :new
    end
  end

  def show; end

  def new
    chatwoot_contact = JSON.parse(params['chatwoot_contact'])
    @contact = current_user.account.contacts.new({
                                                   full_name: chatwoot_contact['name'],
                                                   email: chatwoot_contact['email'],
                                                   phone: chatwoot_contact['phone_number'],
                                                   additional_attributes: { 'chatwoot_id': chatwoot_contact['id'] }
                                                 })
  end

  def create
    @contact = current_user.account.contacts.new(contact_params)

    if @contact.save
      redirect_to account_chatwoot_embed_path(current_user.account, @contact),
                  notice: t('flash_messages.created', model: Contact.model_name.human)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_contact
    @contact = Contact.find(params[:id])
  end

  def contact_params
    params.require(:contact).permit(:full_name, :phone, :email, additional_attributes: {})
  end

  def chatwoot_contact
    @chatwoot_contact ||= JSON.parse(params['chatwoot_contact'])
  end

  def contact_search
    result = current_user.account.contacts.where(
      "additional_attributes->>'chatwoot_id' = ?", chatwoot_contact['id'].to_s
    ).first
    return result if result.present?

    Accounts::Contacts::GetByParams.call(current_user.account,
                                         { email: chatwoot_contact['email'],
                                           phone: chatwoot_contact['phone_number'] })[:ok]
  end
end

app/controllers/accounts/contacts/events_controller.rb
class Accounts::Contacts::EventsController < InternalController
  before_action :set_event, only: %i[show edit update destroy show]
  before_action :set_contact, only: %i[show edit update destroy new]

  def new
    # @event = current_user.account.events.new(event_params.merge({contact: @contact}))
    @event = EventBuilder.new(current_user,
                              event_params.merge({ contact_id: @contact.id, kind: params[:kind],
                                                   deal_id: params[:deal_id] })).build
  end

  def edit; end

  def create
    @event = EventBuilder.new(current_user, event_params).build

    if @event.save
      respond_to do |format|
        format.html do
          redirect_to(new_account_contact_event_path(account_id: current_user.account, contact_id: @event.deal.contact.id,
                                                     deal_id: @event.deal.id))
        end
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @event.destroy
  end

  def update
    @deal = current_user.account.deals.find(params[:deal_id])
    @events = @deal.contact.events
    render :edit, status: :unprocessable_entity unless @event.update(event_params)
  end

  def show; end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = current_user.account.events.find(params[:id])
  end

  def set_contact
    @contact = current_user.account.contacts.find(params[:contact_id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:content, :contact_id, :send_now, :done, :deal_id, :auto_done, :title, :scheduled_at, :from_me, :kind, :app_type,
                                  :app_id, files: [], custom_attributes: {}, additional_attributes: {})
  rescue StandardError
    {}
  end
end

app/controllers/accounts/deal_assignees_controller.rb
class Accounts::DealAssigneesController < InternalController
  before_action :set_deal_assignee, only: %i[destroy]
  before_action :set_deal, only: %i[new]

  def destroy
    return unless @deal_assignee.destroy

    respond_to do |format|
      format.html do
        redirect_to account_deal_path(current_user.account, @deal_assignee.deal),
                    notice: t('flash_messages.deleted', model: DealAssignee.model_name.human)
      end
      format.turbo_stream
    end
  end

  def new
    @deal_assignee = @deal.deal_assignees.new
  end

  def create
    @deal_assignee = DealAssignee.new(deal_assignees_params)
    if @deal_assignee.save
      respond_to do |format|
        format.html { redirect_to account_deal_path(@deal_assignee.account, @deal_assignee.deal) }
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def deal_assignees_params
    params.require(:deal_assignee).permit(:user_id, :deal_id)
  end

  def set_deal
    @deal = Deal.find(params[:deal_id])
  end

  def set_deal_assignee
    @deal_assignee = DealAssignee.find(params[:id])
  end
end

app/controllers/accounts/settings/webhooks_controller.rb
class Accounts::Settings::WebhooksController < InternalController
  before_action :set_webhook, only: %i[edit update destroy]

  def index
    @webhooks = current_user.account.webhooks
    @pagy, @webhooks = pagy(@webhooks)
  end

  def new
    @webhook = Webhook.new
  end

  def create
    @webhook = current_user.account.webhooks.new(webhook_params)
    if @webhook.save
      redirect_to account_webhooks_path(current_user.account),
                  notice: t('flash_messages.created', model: Webhook.model_name.human)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @webhook.update(webhook_params)
      redirect_to edit_account_webhook_path(current_user.account, @webhook),
                  notice: t('flash_messages.updated', model: Webhook.model_name.human)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @webhook.destroy
      flash[:notice] = t('flash_messages.deleted', model: Webhook.model_name.human)
    else
      render :index, status: :unprocessable_entity
    end
  end

  private

  def set_webhook
    @webhook = current_user.account.webhooks.find(params[:id])
  end

  def webhook_params
    params.require(:webhook).permit(:url, :status)
  end
end

app/views/accounts/contacts/_contact.html.erb
<tr id="<%= dom_id(contact, :contact_index_page) %>" is='turbo-frame' class="border-b-2 border-light-palette-p3 last:border-none" data-controller='load-lucid-icons load-flowbite'>
  <td class="py-2.5 pl-4 pr-4 flex-shrink-0">
    <div class="w-[52px] h-[52px] flex">
      <div class="border-2 bg-brand-palette-08 rounded-md h-full w-full flex items-center">
        <i data-lucide="user" class="stroke-dark-gray-palette-p4 m-auto"></i>
      </div>
    </div>
  </td>
  <td class="pr-4 py-2.5 typography-body-r-lh150 text-dark-gray-palette-p2 max-w-[200px] truncate">
    <%= contact.full_name %>
  </td>
  <td class="pr-4 py-2.5 typography-body-r-lh150 text-dark-gray-palette-p2 max-w-[120px] truncate">
    <%= contact.phone %>
  </td>
  <td class="pr-4 py-2.5 typography-body-r-lh150 text-dark-gray-palette-p2 max-w-[200px] truncate">
    <%= contact.email %>
  </td>
  <td class="pr-4 py-2.5 typography-body-r-lh150 text-dark-gray-palette-p2 max-w-[150px] truncate">
    <%= contact.id %>
  </td>
  <td class="pr-4 py-2.5 typography-body-r-lh150 text-dark-gray-palette-p2 max-w-[100px] truncate">
    <%= l(contact.created_at, format: :short) %>
  </td>
  <td class="pr-4 py-2.5 typography-body-r-lh150 text-dark-gray-palette-p2 max-w-[100px] truncate">
    <%= l(contact.updated_at, format: :short) %>
  </td>
  <td class="py-2.5 pl-4 pr-4 sticky right-0 bg-light-palette-p5 z-10">
    <div class="flex justify-end gap-2">
      <button id="dropdownuserBtn_<%= contact.id %>" data-dropdown-toggle="dropdownuserOptions<%= contact.id %>" data-dropdown-placement="left" class="button-default-blank-secondary-icon-only-sm" type="button">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" data-lucide="more-vertical" class="stroke-dark-gray-palette-p3">
          <circle cx="12" cy="12" r="1"></circle>
          <circle cx="12" cy="5" r="1"></circle>
          <circle cx="12" cy="19" r="1"></circle>
        </svg>
      </button>
    </div>
  </td>
</tr>
<div id="dropdownuserOptions<%= contact.id %>" class="z-50 hidden bg-white divide-y divide-gray-200 rounded-lg shadow w-48 absolute dark:bg-gray-700">
  <ul class="py-2 typography-text-m-lh150 text-dark-gray-palette-p3 dark:text-gray-200" aria-labelledby="dropdownDefaultButton">
    <li>
      <%= link_to account_contact_path(Current.account, contact), class: "flex items-center space-x-2 px-4 py-2 hover:bg-gray-200 hover:text-dark-gray-palette-p1 dark:hover:bg-gray-600 dark:hover:text-white", data: { turbo_frame: :drawer } do %>
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" data-lucide="info">
          <circle cx="12" cy="12" r="10"></circle>
          <path d="M12 16v-4"></path>
          <path d="M12 8h.01"></path>
        </svg>
        <p>
          <%= t('activerecord.models.show') %>
        </p>
      <% end %>
    </li>
    <li>
      <%= link_to edit_account_contact_path(Current.account, contact), class: "flex items-center space-x-2 px-4 py-2 hover:bg-gray-200 hover:text-dark-gray-palette-p1 dark:hover:bg-gray-600 dark:hover:text-white", data: { turbo_frame: :drawer } do %>
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" data-lucide="pencil">
          <path d="M17 3a2.85 2.83 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5Z"></path>
          <path d="m15 5 4 4"></path>
        </svg>
        <p>
          <%= t('activerecord.models.edit') %>
        </p>
      <% end %>
    </li>
    <li>
      <%= link_to  account_contact_path(current_user.account, contact), method: :delete, data: { confirm: t('views.accounts.contacts.contact.are_you_sure?') }, class: "flex items-center space-x-2 px-4 py-2 hover:bg-gray-200 hover:text-dark-gray-palette-p1 dark:hover:bg-gray-600 dark:hover:text-white" do %>
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" data-lucide="trash">
          <path d="M3 6h18"></path>
          <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6"></path>
          <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2"></path>
        </svg>
        <p>
          <%= t('activerecord.models.delete') %>
        </p>
      <% end %>
    </li>
  </ul>
</div>

app/views/accounts/contacts/_drawer_show_contact.html.erb
<% content_for :show_additional_content do %>
  <div class="bg-light-palette-p5 border-2 border-neutral-150 border-light-palette-p3 rounded ">
    <div class="">
      <header class="border-b-2 border-neutral-100 flex flex-wrap items-center p-4">
        <div class="flex text-dark-gray-palette-p1 typography-body-s-lh150">
          <h1>
            <%= t('activerecord.models.deal.other') %>
          </h1>
        </div>
      </header>
      <ul class="p-4 flex flex-col " >
        <% contact.deals.each do |deal| %>
          <%= content_tag :li, id: dom_id(deal), class: "grid gap-5 border-b-2 border-light-palette-p3 last:border-none py-5 first:pt-0 last:pb-0", data: {controller: 'load-lucid-icons'} do %>
            <div class= "flex items-center gap-4">
              <div class="p-2.5 rounded-lg border-2 border-light-palette-p3 typography-text-m-lh150 text-dark-gray-palette-p3  dark:text-gray-200">
                <%= embedded_svg("deals-icon.svg", class: "w-4") %>
              </div>
              <div class="mr-auto">
                <div class="flex flex-col">
                  <h2 class="typography-text-s-lh150 text-dark-gray-palette-p1">
                    <%= deal.name %>
                  </h2>
                </div>
              </div>
              <%= link_to account_deal_path(Current.account, deal), data: {turbo_frame: :_top} , class: 'flex items-center justify-center rounded text-gray-pallete-p3 w-8 h-8 hover:bg-light-palette-p4 hover:text-dark-gray-palette-p1 dark:hover:bg-gray-600 dark:hover:text-white' do %>
                <i data-lucide="arrow-right"></i>
              <% end %>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>
<%= render 'components/show_model', model: contact, edit_path: edit_account_contact_path(Current.account, contact) %>

app/views/accounts/contacts/_form.html.erb
<%= form_for([current_user.account, contact], html:{class: "flex flex-col gap-5"}) do | form | %>
  <% if contact.errors.any? %>
    <div>
      <ul>
        <% contact.errors.each do |error| %>
          <li class="typography-body-s-lh150 text-auxiliary-palette-red"><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <h2 class= "typography-body-s-lh150 text-dark-gray-palette-p1">
    <%= t('views.accounts.contacts.form.contact_data') %>
  </h2>
  <div class= "grid 2xl:grid-cols-6 gap-4">
    <div class="flex flex-col 2xl:col-span-4 gap-1">
      <%= form.label :full_name, class: "typography-text-m-lh150 text-dark-gray-palette-p1" %>
      <%= form.text_field :full_name, placeholder: "João Paulo", class: 'form-input' %>
    </div>
    <div class="flex flex-col 2xl:col-span-2 gap-1">
      <%= form.label :phone, class: "typography-text-m-lh150 text-dark-gray-palette-p1"  %>
      <%= form.text_field :phone, placeholder: "+5522999999999", class: 'form-input', data: {controller: "input-mask--input-phone"} %>
    </div>
  </div>
  <div class="flex flex-col gap-1">
    <%= form.label :email, class: "typography-text-m-lh150 text-dark-gray-palette-p1"  %>
    <%= form.text_field :email, placeholder: "joaopaulo@email.com", class: 'form-input' %>
  </div>
  <div class="flex flex-col gap-1">
    <%= form.label :label_list, class: "typography-text-m-lh150 text-dark-gray-palette-p1"  %>
    <%= form.text_field :label_list,  value: contact.labels.join(', '), placeholder: t('views.accounts.contacts.form.tag_placeholder'), class: 'form-input !border-light-palette-p3', data: {controller: 'tag-input'}%>
  </div>
  <!-- <div class="grid">
    <label class= "typography-text-m-lh150 text-dark-gray-palette-p1">Labels</label>
    <select disabled class="form-input" multiple="">
      <%= contact.labels.each do | label | %>
        <option selected><%= label.name %></option>
      <% end %>
    </select>
  </div> -->
  <div class="h-0.5 w-full bg-light-palette-p3"></div>
  <h2 class= "typography-body-s-lh150 text-dark-gray-palette-p1">
    <%= t('activerecord.attributes.contact.chatwoot_conversations_label_list') %>
  </h2>
  <% if contact.chatwoot_conversations_labels.empty? %>
    <p class="typography-text-m-lh150 text-dark-gray-palette-p1">
      <%= t('views.accounts.contacts.form.chatwoot_conversations_label_list_empty') %>
    </p>
  <% else %>
    <%= render 'components/list_labels', labels: contact.chatwoot_conversations_label_list, max_width: 'none', justify_content: 'start' %>
  <% end %>
  <div class="h-0.5 w-full bg-light-palette-p3"></div>
  <%= render 'accounts/custom_attributes', m: contact, f: form %>
  <div class="flex gap-2 self-end">
    <%= link_to account_custom_attributes_definitions_path(current_user.account), class:"btn-secondary flex items-center gap-2", data:{ turbo_frame: :_top } do %>
      <i data-lucide="plus"></i>
      <%= t('activerecord.models.custom_attribute_definition.add') %>
    <% end %>
    <%= form.submit class: 'btn-primary cursor-pointer' %>
  </div>
<% end %>

app/views/accounts/contacts/hovercard_preview.html.erb
<%= turbo_frame_tag dom_id(@contact, :hovercard_preview) do %>
  <%= render '/components/contacts/card_preview', contact: @contact, details_url: account_contact_path(Current.account, @contact) %>
<% end %>

app/views/accounts/contacts/show.html.erb
<%= render '/accounts/contacts/drawer_show_contact', contact: @contact %>