config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Motor::Admin => '/motor_admin'
  mount Sidekiq::Web => '/sidekiq'
  mount GoodJob::Engine => 'good_job'

  draw(:installation)

  resources :accounts, module: :accounts do
    resources :webpush_subscriptions, only: [:create]
    resources :settings, only: [:index]
    resources :welcome, only: [:index]
    resources :custom_attributes_definitions, module: :settings do
    end

    resources :webhooks, module: :settings do
    end

    resources :users do
      get 'select_user_search', on: :collection
    end
    resources :products do
      get 'edit_custom_attributes', on: :member
      patch 'update_custom_attributes', on: :member
      get 'select_product_search', on: :collection
    end
    resources :contacts do
      get 'search', to: 'contacts#search', on: :collection
      get 'edit_custom_attributes'
      get 'chatwoot_conversation_link', on: :member
      patch 'update_custom_attributes'
      get 'select_contact_search', on: :collection
      resources :events, module: :contacts do
      end
      namespace :events, module: :contacts do
        namespace :apps, module: :events do
        end
      end

      collection do
        resources :chatwoot_embed, only: %i[show new create], controller: 'contacts/chatwoot_embed' do
          post 'search', on: :collection
        end
      end
      get 'hovercard_preview', on: :member
    end
    resources :pipelines do
      get 'import'
      post 'import_file'
      get 'export'
      member do
        get 'new_bulk_action'
        get 'bulk_action'
        post 'create_bulk_action'
      end
    end

    resources :deals do
      patch 'update_deal_product', on: :member
      get 'edit_deal_product', on: :member
      get 'deal_products', on: :member
      get 'deal_assignees', on: :member
      get 'events_to_do', on: :member
      get 'events_done', on: :member
      get 'add_contact'
      post 'commit_add_contact'
      delete 'remove_contact'
      get 'new_select_contact', on: :collection
      get 'edit_custom_attributes'
      patch 'update_custom_attributes'
    end
    resources :deal_products, only: %i[destroy new create]
    resources :deal_assignees, only: %i[destroy new create]

    namespace :apps do
      resources :evolution_apis do
        member do
          get 'pair_qr_code'
          post 'refresh_qr_code'
        end
      end
      resources :chatwoots
      # resources :events, module: :contacts
      resource :ai_assistent, only: %i[edit update]
    end
    resources :attachments, only: [:destroy]
    resources :stages, only: [:show]
  end
  if ENV.fetch('ENABLE_USER_SIGNUP', 'false') == 'true'
    devise_for :users, controllers: {
      registrations: 'users/registrations'
    }
  else
    devise_for :users, skip: [:registrations]
  end

  root to: 'accounts/pipelines#index'

  namespace :api do
    namespace :v1 do
      resources :accounts, module: :accounts do
        resources :deals, only: %i[show create update] do
          post 'upsert', on: :collection
          resources :events, only: [:create], module: :deals do
          end
        end
        resources :contacts, only: %i[show create] do
          post 'upsert', on: :collection
          match 'search', on: :collection, via: %i[get post]
        end
        namespace :apps do
          # resources :events, module: :contacts
        end
        resources :deal_products, only: %i[create show]
        resources :products, only: %i[create show] do
          match 'search', on: :collection, via: %i[get post]
        end
      end

      resources :contacts, only: [:create] do
      end
    end
  end

  namespace :embedded do
    resources :accounts, module: :accounts do
      namespace :apps do
        resources :chatwoots, only: [:index] do
        end
      end
    end
  end

  namespace :apps do
    resources :chatwoots do
      collection do
        post 'webhooks'
        get 'embedding'
        get 'embedding_init_authenticate'
        post 'embedding_authenticate'
      end
    end
    resources :evolution_apis do
      collection do
        post 'webhooks'
      end
    end
  end
  get 'service-worker' => 'pwa#service_worker'
  get 'webmanifest' => 'pwa#manifest'
end

app/controllers/accounts/apps/ai_assistents_controller.rb
# frozen_string_literal: true

class Accounts::Apps::AiAssistentsController < InternalController
  before_action :set_ai_assistent

  def edit; end

  def update
    if @ai_assistent.update(ai_assistent_params)
      redirect_to edit_account_apps_ai_assistent_path(current_user.account),
                  notice: t('flash_messages.updated', model: Apps::AiAssistent.model_name.human)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_ai_assistent
    @ai_assistent = Apps::AiAssistent.first.presence || Apps::AiAssistent.create
  end

  def ai_assistent_params
    params.require(:apps_ai_assistent).permit(:auto_reply, :model, :api_key, :enabled)
  end
end

app/controllers/accounts/apps/chatwoots_controller.rb
class Accounts::Apps::ChatwootsController < InternalController
  before_action :set_chatwoot, only: %i[edit update destroy]

  def new
    if current_user.account.apps_chatwoots.blank?
      @chatwoot = current_user.account.apps_chatwoots.new
    else
      redirect_to edit_account_apps_chatwoot_path(current_user.account, current_user.account.apps_chatwoots.first)
    end
  end

  def edit; end

  def create
    result = Accounts::Apps::Chatwoots::Create.call(current_user.account, chatwoot_params)
    @chatwoot = result[result.keys.first]
    if result.key?(:ok)
      redirect_to edit_account_apps_chatwoot_path(current_user.account, @chatwoot),
                  notice: t('flash_messages.created', model: Apps::Chatwoot.model_name.human)
    else
      render :new
    end
  end

  def destroy
    result = Accounts::Apps::Chatwoots::Delete.call(current_user.account, @chatwoot)
    if result.key?(:ok)
      redirect_to account_settings_path(current_user.account),
                  notice: t('flash_messages.deleted', model: Apps::Chatwoot.model_name.human)
    end
  end

  def update
    @chatwoot.update(chatwoot_params)
    redirect_to edit_account_apps_chatwoot_path(current_user.account, current_user.account.apps_chatwoots.first)
  end

  private

  def set_chatwoot
    @chatwoot = current_user.account.apps_chatwoots.first
  end

  def chatwoot_params
    params.require(:apps_chatwoot).permit(:chatwoot_endpoint_url, :chatwoot_account_id, :chatwoot_user_token, :active)
  end
end

app/controllers/accounts/apps/evolution_apis_controller.rb
class Accounts::Apps::EvolutionApisController < InternalController
  before_action :set_evolution_api, only: %i[edit update refresh_qr_code pair_qr_code destroy]

  def new
    @evolution_api = Apps::EvolutionApi.new
  end

  def create
    result = Accounts::Apps::EvolutionApis::Create.call(current_user, evolution_api_params)
    @evolution_api = result[result.keys.first]
    if result.key?(:ok)
      redirect_to pair_qr_code_account_apps_evolution_api_path(current_user.account, @evolution_api.id)
    else
      @evolution_api = result[:error]
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @evolution_apis = current_user.account.apps_evolution_apis.order(updated_at: :desc)
    @pagy, @evolution_apis = pagy(@evolution_apis)
  end

  def edit; end

  def update
    if @evolution_api.update(evolution_api_params)
      flash[:notice] = t('flash_messages.updated', model: Apps::EvolutionApi.model_name.human)
      redirect_to edit_account_apps_evolution_api_path(current_user.account, @evolution_api)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def refresh_qr_code
    @evolution_api.update({
                            instance: @evolution_api.generate_token('instance'),
                            token: @evolution_api.generate_token('token')
                          })

    Accounts::Apps::EvolutionApis::Instance::Create.call(@evolution_api)
  end

  def destroy
    if @evolution_api.destroy
      respond_to do |format|
        format.html do
          redirect_to account_apps_evolution_apis_path(current_user.account),
                      notice: t('flash_messages.deleted', model: Apps::EvolutionApi.model_name.human)
        end
        format.turbo_stream
      end
    end
  end

  def pair_qr_code; end

  private

  def set_evolution_api
    @evolution_api = current_user.account.apps_evolution_apis.find(params[:id])
  end

  def evolution_api_params
    params.require(:apps_evolution_api).permit(:name)
  end
end

app/controllers/accounts/apps_controller.rb
class Accounts::AppsController < InternalController
  before_action :set_contact, only: %i[show edit update destroy]

  # GET /contacts or /contacts.json
  def index
    @apps = current_user.account.apps
    @pagy, @apps = pagy(@apps)
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit; end

  # POST /contacts or /contacts.json
  def create
    @contact = current_user.account.contacts.new(contact_params)

    if @contact.save
      redirect_to account_contact_path(current_user.account, @contact),
                  notice: t('flash_messages.created', model: Contact.model_name.human)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        redirect_to account_contact_path(current_user.account, @contact),
                    notice: t('flash_messages.updated', model: Contact.model_name.human)
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html do
        redirect_to contacts_url, notice: t('flash_messages.deleted', model: Contact.model_name.human)
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_contact
    @contact = Contact.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def contact_params
    params.require(:contact).permit(:full_name, :phone, :email, custom_attributes: {})
  end
end

app/controllers/accounts/attachments_controller.rb
class Accounts::AttachmentsController < InternalController
  before_action :set_attachment, only: %i[destroy]

  def destroy
    @attachment.destroy
    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  def set_attachment
    @attachment = Attachment.find(params[:id])
  end
end

app/controllers/accounts/contacts/chatwoot_embed_controller.rb
class Accounts::Contacts::ChatwootEmbedController < InternalController
  layout 'embed'
  before_action :set_contact, only: %i[show]

  def search
    contact = contact_search

    if contact.present?
      redirect_to account_chatwoot_embed_path(current_user.account, contact)
    else
      chatwoot_contact = JSON.parse(params['chatwoot_contact'])
      @contact = current_user.account.contacts.new({
                                                     full_name: chatwoot_contact['name'],
                                                     email: chatwoot_contact['email'],
                                                     phone: chatwoot_contact['phone_number'],
                                                     additional_attributes: { 'chatwoot_id': chatwoot_contact['id'] }
                                                   })
      render :new
    end
  end

  def show; end

  def new
    chatwoot_contact = JSON.parse(params['chatwoot_contact'])
    @contact = current_user.account.contacts.new({
                                                   full_name: chatwoot_contact['name'],
                                                   email: chatwoot_contact['email'],
                                                   phone: chatwoot_contact['phone_number'],
                                                   additional_attributes: { 'chatwoot_id': chatwoot_contact['id'] }
                                                 })
  end

  def create
    @contact = current_user.account.contacts.new(contact_params)

    if @contact.save
      redirect_to account_chatwoot_embed_path(current_user.account, @contact),
                  notice: t('flash_messages.created', model: Contact.model_name.human)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_contact
    @contact = Contact.find(params[:id])
  end

  def contact_params
    params.require(:contact).permit(:full_name, :phone, :email, additional_attributes: {})
  end

  def chatwoot_contact
    @chatwoot_contact ||= JSON.parse(params['chatwoot_contact'])
  end

  def contact_search
    result = current_user.account.contacts.where(
      "additional_attributes->>'chatwoot_id' = ?", chatwoot_contact['id'].to_s
    ).first
    return result if result.present?

    Accounts::Contacts::GetByParams.call(current_user.account,
                                         { email: chatwoot_contact['email'],
                                           phone: chatwoot_contact['phone_number'] })[:ok]
  end
end

app/controllers/accounts/contacts/events_controller.rb
class Accounts::Contacts::EventsController < InternalController
  before_action :set_event, only: %i[show edit update destroy show]
  before_action :set_contact, only: %i[show edit update destroy new]

  def new
    # @event = current_user.account.events.new(event_params.merge({contact: @contact}))
    @event = EventBuilder.new(current_user,
                              event_params.merge({ contact_id: @contact.id, kind: params[:kind],
                                                   deal_id: params[:deal_id] })).build
  end

  def edit; end

  def create
    @event = EventBuilder.new(current_user, event_params).build

    if @event.save
      respond_to do |format|
        format.html do
          redirect_to(new_account_contact_event_path(account_id: current_user.account, contact_id: @event.deal.contact.id,
                                                     deal_id: @event.deal.id))
        end
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @event.destroy
  end

  def update
    @deal = current_user.account.deals.find(params[:deal_id])
    @events = @deal.contact.events
    render :edit, status: :unprocessable_entity unless @event.update(event_params)
  end

  def show; end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = current_user.account.events.find(params[:id])
  end

  def set_contact
    @contact = current_user.account.contacts.find(params[:contact_id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:content, :contact_id, :send_now, :done, :deal_id, :auto_done, :title, :scheduled_at, :from_me, :kind, :app_type,
                                  :app_id, files: [], custom_attributes: {}, additional_attributes: {})
  rescue StandardError
    {}
  end
end

app/controllers/accounts/deal_assignees_controller.rb
class Accounts::DealAssigneesController < InternalController
  before_action :set_deal_assignee, only: %i[destroy]
  before_action :set_deal, only: %i[new]

  def destroy
    return unless @deal_assignee.destroy

    respond_to do |format|
      format.html do
        redirect_to account_deal_path(current_user.account, @deal_assignee.deal),
                    notice: t('flash_messages.deleted', model: DealAssignee.model_name.human)
      end
      format.turbo_stream
    end
  end

  def new
    @deal_assignee = @deal.deal_assignees.new
  end

  def create
    @deal_assignee = DealAssignee.new(deal_assignees_params)
    if @deal_assignee.save
      respond_to do |format|
        format.html { redirect_to account_deal_path(@deal_assignee.account, @deal_assignee.deal) }
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def deal_assignees_params
    params.require(:deal_assignee).permit(:user_id, :deal_id)
  end

  def set_deal
    @deal = Deal.find(params[:deal_id])
  end

  def set_deal_assignee
    @deal_assignee = DealAssignee.find(params[:id])
  end
end

app/controllers/accounts/settings/webhooks_controller.rb
class Accounts::Settings::WebhooksController < InternalController
  before_action :set_webhook, only: %i[edit update destroy]

  def index
    @webhooks = current_user.account.webhooks
    @pagy, @webhooks = pagy(@webhooks)
  end

  def new
    @webhook = Webhook.new
  end

  def create
    @webhook = current_user.account.webhooks.new(webhook_params)
    if @webhook.save
      redirect_to account_webhooks_path(current_user.account),
                  notice: t('flash_messages.created', model: Webhook.model_name.human)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @webhook.update(webhook_params)
      redirect_to edit_account_webhook_path(current_user.account, @webhook),
                  notice: t('flash_messages.updated', model: Webhook.model_name.human)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @webhook.destroy
      flash[:notice] = t('flash_messages.deleted', model: Webhook.model_name.human)
    else
      render :index, status: :unprocessable_entity
    end
  end

  private

  def set_webhook
    @webhook = current_user.account.webhooks.find(params[:id])
  end

  def webhook_params
    params.require(:webhook).permit(:url, :status)
  end
end

app/views/accounts/stages/_kanban_details.html.erb
<div class='flex items-center justify-between gap-1.5' id='stage-<%= stage.id %>-<%= filter_status_deal %>-kaban-details'>
  <p class='typography-body-900 color-fg-default cursor-default truncate' data-tooltip-target="tooltip-stage-<%= stage.id %>-deals-total-amount" data-tooltip-placement="bottom">
    <%= stage.total_amount_deals_at_format(filter_status_deal) %>
  </p>
  <div id="tooltip-stage-<%= stage.id %>-deals-total-amount" role="tooltip" class="absolute z-10 invisible inline-block px-3 py-2 typography-label-900 font-medium text-white transition-opacity duration-300 bg-gray-900 rounded-lg shadow-xs opacity-0 tooltip dark:bg-gray-700">
    <%= stage.total_amount_deals_at_format(filter_status_deal) %>
    <div class="tooltip-arrow" data-popper-arrow></div>
  </div>
  <p class='py-0.5 px-1 typography-button-800 color-bg-fill-hard color-fg-highlight rounded-lg cursor-default' data-tooltip-target="tooltip-stage-<%= stage.id %>-deals-total_quantity" data-tooltip-placement="bottom">
    <%= stage.total_quantity_deals_resume(filter_status_deal) %>
  </p>
  <div id="tooltip-stage-<%= stage.id %>-deals-total_quantity" role="tooltip" class="absolute z-10 invisible inline-block px-3 py-2 typography-label-900 font-medium text-white transition-opacity duration-300 bg-gray-900 rounded-lg shadow-xs opacity-0 tooltip dark:bg-gray-700">
    <%= stage.total_quantity_deals(filter_status_deal) %>
    <div class="tooltip-arrow" data-popper-arrow></div>
  </div>
</div>

app/views/accounts/stages/_stage.html.erb
<div class="px-4 pb-4 rounded border-2 border-light-palette-p3 bg-light-palette-p5 relative" data-controller="load-lucid-icons load-flowbite" id=<%= dom_id(stage, filter_status_deal) %>>
  <div class='pt-2 pb-3.5 flex flex-col gap-1'>
    <div class="flex justify-between items-center gap-1.5">
      <h1 class="typography-text-s-lh150 color-fg-default truncate cursor-default" data-tooltip-target="tooltip-name-<%= stage.id %>" data-tooltip-placement="bottom">
        <%= stage.name %>
      </h1>
      <div id="tooltip-name-<%= stage.id %>" role="tooltip" class="absolute z-10 invisible inline-block px-3 py-2 typography-label-900 font-medium text-white transition-opacity duration-300 bg-gray-900 rounded-lg shadow-xs opacity-0 tooltip dark:bg-gray-700">
        <%= stage.name %>
        <div class="tooltip-arrow" data-popper-arrow></div>
      </div>
      <button id="dropdownMenuIconHorizontalButton" data-dropdown-toggle="dropdownDotsHorizontal<%=stage.id%>" class="button-default-blank-secondary-icon-only-sm" type="button">
        <i data-lucide="more-horizontal"></i>
      </button>
      <div class="p-0 w-6 rounded-tr-lg absolute border-t-2 border-r-2 border-light-palette-p3 left-[285px] bg-light-palette-p5 rotate-45">
        <i data-lucide="chevron-right" class="text-light-palette-p1 -rotate-45 w-5"></i>
      </div>
    </div>
    <!-- Dropdown menu -->
    <div id="dropdownDotsHorizontal<%=stage.id%>" class="z-10 hidden left-16 bg-white divide-y divide-gray-300 rounded-lg shadow w-48 dark:bg-gray-700">
      <ul class="py-2 typography-text-m-lh150 text-dark-gray-palette-p3  dark:text-gray-200" aria-labelledby="dropdownDefaultButton">
        <li>
          <%= link_to bulk_action_account_pipeline_path(Current.account, stage.pipeline.id, stage_id: stage.id), class: "flex items-center space-x-2 px-4 py-2 hover:bg-gray-300 dark:hover:bg-gray-600 hover:text-dark-gray-palette-p1 dark:hover:text-white", data: { turbo_frame: 'modal' } do %>
            <i data-lucide="layers"></i>
            <p>
              <%= t('views.accounts.pipelines.stage.bulk_action') %>
              <b class="typography-micro-b-lh150 text-dark-palette-p3 text-[6px]"> BETA </b>
            </p>
          <% end %>
        </li>
        <li>
          <%= link_to account_pipeline_import_path(Current.account, stage.pipeline.id, stage_id: stage.id), class: "flex items-center space-x-2 px-4 py-2 hover:bg-gray-300 dark:hover:bg-gray-600 hover:text-dark-gray-palette-p1 dark:hover:text-white", data: {controller: 'change-request-to-turbo-stream', action: 'click->change-request-to-turbo-stream#changeHeader'} do%>
            <i data-lucide="file-input"></i>
            <p>
              <%= t('views.accounts.pipelines.stage.import_deals') %>
            </p>
          <%end%>
        </li>
        <%# <li>
      <a href="#" class="flex items-center space-x-2 px-4 py-2 hover:bg-gray-300 dark:hover:bg-gray-600 hover:text-dark-gray-palette-p1 dark:hover:text-white" ><i data-lucide="file-output"></i>
        <p>Exportar negócios</p>
      </a>
    </li> %>
      </ul>
    </div>
    <%= render 'accounts/stages/kanban_details', stage: stage, filter_status_deal: params[:filter_status_deal] %>
  </div>
  <ul data-controller="drag" data-drag-url="/accounts/:account_id/deals/:deal_id" data-id="<%= stage.id %>" class="space-y-4 overflow-y-auto custom-scroll-list-deal h-[calc(100vh-260px)]" id=<%= dom_id(stage, :deals) %>>
    <%= render partial: 'accounts/pipelines/deal', collection: deals, as: :deal %>
    <% if pagy.next.present? %>
      <%= turbo_frame_tag dom_id(stage, :pagination_deals), src: account_stage_path(Current.account, stage, filter_status_deal: filter_status_deal, page: pagy.next, format: :turbo_stream), loading: :lazy do  %>
        <div class='py-5'>
          <%= render '/components/loading' %>
        </div>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/accounts/stages/show.html.erb
<%= turbo_frame_tag @stage do %>
  <%= render 'stage', filter_status_deal: @filter_status_deal, stage: @stage, deals: @deals, pagy: @pagy %>
<% end %>

app/views/accounts/stages/show.turbo_stream.erb
<%= turbo_stream.append dom_id(@stage, :deals) do %>
  <% @deals.each do |deal| %>
    <%= render partial: 'accounts/pipelines/deal', locals: {deal: deal} %>
  <% end %>
  <% if @pagy.next.present? %>
    <%= turbo_frame_tag dom_id(@stage, :pagination_deals), src: account_stage_path(Current.account, @stage, filter_status_deal: @filter_status_deal, page: @pagy.next, format: :turbo_stream), loading: :lazy do  %>
      <div class='py-5'>
        <%= render '/components/loading' %>
      </div>
    <% end %>
  <% end %>
<% end %>
<% unless @pagy.next.present? %>
  <%= turbo_stream.remove dom_id(@stage, :pagination_deals) %>
<% end %>